### ISSUE TITLE
Make DevX Oncall alerts less noisy

### ISSUE THREAD

**Issue by ZainRizvi** [pytorch/test-infra#1083]
We have three types of noise we want to remove:

- [x] ~~Only alerts for workflows that block viable/strict upgrades should fire~~ https://github.com/pytorch/test-infra/issues/3828
- [x] When two sequential jobs fail with different failures, those should not be considered a continuation of the same failure
- [x] If two jobs fail with the same flaky error, while there is an in progress job in between them, should that really trigger an alert?
- [x] When jobs stop failing, we should not notify on them at all

**Comment by huydhn** [comment]
AI: Nightly alarm is currently assigned to OSS oncall as well

**Comment by huydhn** [comment]
I will move the first point `Only alerts for workflows that block viable/strict upgrades should fire` into a separate issue because I think I will keep the current behavior of getting alert message for `periodic` and `inductor` for now.  The first is to not forget about periodic, while the latter is inline with my future plan to allow teams to subscribe to their alerts, i.e. DevX subscribes to pull /trunk/periodic, complier subscribes to inductor, etc.  So more planning would be needed for that first point.

**Comment by huydhn** [comment]
Resolving the issue now as all tasks have been addressed
