### ISSUE TITLE
mergebot has inconsistent behavior on comment edit

### ISSUE THREAD

**Issue by suo** [pytorch/test-infra#360]
1. If you edit a merge comment, nothing will happen.
2. If you edit a revert comment, the `trymerge.py` workflow will fail, just because you edited the command.
3. If you edit a merge pull request review, we will dispatch an entirely new workflow.

These are three different behaviors, we should pick one and implement it consistently.

My vote is that edits should be allowed, they should dispatch an entirely new workflow, and we should make sure that the workflows have concurrency rules implemented so that the more recent ones pre-empt the older ones.

**Comment by zengk95** [comment]
@suo I kinda like the edit check in try merge as a means to cancel the workflow since I accidentally reverted before and then edited it and it was able to stop it. But at the same time, I'm pretty sure most people don't know about it so they wouldn't use it like that. @malfet I think you wrote that logic earlier. What do you think about removing the check?

**Comment by suo** [comment]
As an aside, I wonder if we should be more explicit with our response to users. So instead of just a +1, the bot can comment saying we began the merge/revert/rebase process and provide a link to the relevant workflow. That would allow people to cancel the workflow themselves if they want.

**Comment by ZainRizvi** [comment]
Fixed by the above PR
