### ISSUE TITLE
Bot should not re-request review if user closes and then reopens PR

### ISSUE THREAD

**Issue by ezyang** [pytorch/test-infra#3869]
self explanatory

**Comment by ezyang** [comment]
I don't know, all I know is the bot comes and removes approves sometimes

**Comment by clee2000** [comment]
afaik the only code we have that removes approvals is the one that removes approvals from PRs of authors without write permissions on re open (https://github.com/pytorch/test-infra/pull/4782) but this was added after this issue got made.  

The only other things I know of that assign approvers are the codeowners file and the auto request review workflow.  

I'm going to close this since I haven't seen this happen before.  If you see it happen, please reopen with a screenshot or a link
