### ISSUE TITLE
rebase + merge gets rid of the commit author

### ISSUE THREAD

**Issue by janeyx99** [pytorch/test-infra#406]
If you @pytorchbot rebase before you merge, the user name doesn’t show up as an author:
![image](https://user-images.githubusercontent.com/31798555/173155866-d574b2b8-30b1-4a48-a6de-b78325372f9d.png)

https://github.com/pytorch/pytorch/pull/79302 is the commit in question.

cc @clee2000

**Comment by seemethere** [comment]
![Screen Shot 2022-06-30 at 1 39 07 PM](https://user-images.githubusercontent.com/1700823/176774497-e29e6ffb-bc77-4eb5-8fee-f5a1e4bbec24.png)

Rebase commits appear to be fully owned by pytorchmergebot which might be causing the issue here.

From https://github.com/pytorch/pytorch/pull/78918/commits

**Comment by clee2000** [comment]
should be fixed by https://github.com/pytorch/pytorch/pull/80747
reopen if not
