### ISSUE TITLE
Green highlighting seems highly inconsistent

### ISSUE THREAD

**Issue by ezyang** [pytorch/test-infra#4257]
In https://hud.pytorch.org/benchmark/timm_models/inductor_dynamic?startTime=Thu,%2004%20May%202023%2018:54:50%20GMT&stopTime=Sat,%2003%20Jun%202023%2018:54:50%20GMT&granularity=day&mode=training&dtype=amp&lBranch=main&lCommit=8215468870daae5a1da7ac02f98f4e2ddf2d7623&rBranch=main&rCommit=03de15806e5d27ee4ef6d82dbcc66dac78f6e3bf lcnet improved speedup 0.9763 → 1.2536 but it was not highlighted green. Why not?

cc @huydhn

**Comment by huydhn** [comment]
In this case, the dashboard only highlights the change if the old value was smaller than the speedup threshold 0.95 AND the new value was larger indicating that an acceptable level of speedup has been achieved.  The logic is defined here https://github.com/pytorch/test-infra/blob/main/torchci/pages/benchmark/%5Bsuite%5D/%5Bcompiler%5D/%5B%5B...page%5D%5D.tsx#L422-L424.  Thus, `0.9763 → 1.2536` wasn't highlight as both values were larger than 0.95.

So, I have several thoughts on this:

* If this is a source of confusion.  We can tweak the logic so that green means increase (more than a percentage threshold) and red means decrease (again, more than a percentage threshold)
* Or we can keep the behavior, but set the threshold to be 1.0 instead

**Comment by ezyang** [comment]
My intuition is that as oncall, I want to look for models that got faster, so I just want an increase more than a percentage threshold, or whatever we define to be "substantive" (since if a model is noisy, it might be hard to set that bar.)

The current logic seems completely useless to me; in the steady state I expect all of our models to be doing 1x or better; even if I went from 1.2x to 100000x it would never be highlighted as green, that seems... wrong?
