### ISSUE TITLE
Update the geomean computation implementation

### ISSUE THREAD

**Issue by desertfire** [pytorch/test-infra#4270]
Sorry for the churn, but in today's PT2 core weekly meeting, we had another discussion on how the geomean should be computed for our dashboard numbers. Most of us prefer to not using clipping for our benchmark results, meaning: 1) excluding failed test from the computation instead of using 1.0; 2) not clipping <1.0 speedup to 1.0. Meanwhile, we are actively working on bringing the pass rate to 100%.

cc @jansel @ezyang @eellison @gchanan

**Comment by huydhn** [comment]
Sound good.  I will bring back the previous geomean implementation without clipping.  Also, do you have any public wiki page on how these metrics are calculated that I can refer to?  The idea is that I could include a link to that page so that external contributors who use the page could quickly see what are measured and their meaning.

**Comment by huydhn** [comment]
https://pytorch.org/docs/main/compile/performance-dashboard.html
