### ISSUE TITLE
DrCI fails to identify test as broken on trunk

### ISSUE THREAD

**Issue by malfet** [pytorch/test-infra#4328]
From https://github.com/pytorch/pytorch/pull/104214 DrCI identifies `test_sparse_semi_structured` as NEW failure, even though it is caused by trunk failures introduced by https://github.com/pytorch/pytorch/commit/cf5262a84f815c1e574883bc244333d0d211c7a2 that was later reverted

Hud link: https://hud.pytorch.org/pytorch/pytorch/pull/104214?sha=dd52521aa51e4d609fb97b6a4cf657fc89c49308

<img width="756" alt="image" src="https://github.com/pytorch/test-infra/assets/2453524/8fa863e8-d419-41cb-a85d-6250e76e2809">
<img width="1331" alt="image" src="https://github.com/pytorch/test-infra/assets/2453524/0da32361-b7be-491e-a39e-463061d41ea4">

**Comment by huydhn** [comment]
Just a note, this discrepancy happens because the failed test was run in 2 different shards, thus simply comparing job names between didn't match

**Comment by huydhn** [comment]
There is another issue with comparing job names is that the suffix like unstable is also included.  As the suffix is added dynamically by checking the open/close status of the corresponding unstable issue.  This also leads to discrepancy, i.e. https://github.com/pytorch/pytorch/pull/104067 has a new failure for [linux-bionic-cuda12.1-py3.10-gcc9 / test (deploy, 1, 1, linux.4xlarge.nvidia.gpu)](https://hud.pytorch.org/pr/pytorch/pytorch/104067#14667979223) ([gh](https://github.com/pytorch/pytorch/actions/runs/5415919694/jobs/9845849796)).  Its base commit as the same failure https://hud.pytorch.org/pytorch/pytorch/commit/67babf7a4514f38a1f96fbaf947d357097c2c4d8 but has the suffix `linux-bionic-cuda12.1-py3.10-gcc9 / test (deploy, 1, 1, linux.4xlarge.nvidia.gpu, unstable)` because https://github.com/pytorch/pytorch/issues/103654 was open at that time
