### ISSUE TITLE
[TorchFix] requires_grad check fails when condition

### ISSUE THREAD

**Issue by EgShes** [pytorch/test-infra#4687]
TorchFix failes to detect requres_grad mistyping when using condition instead of plain bool value

Here is the code to reproduce
```python
import torch.nn as nn
model = nn.Module()

for name, param in model.named_parameters():
    param.require_grad = 'specific_layer' in name
```

TorchFix version: 0.1.1

**Comment by kit1980** [comment]
The problem is that currently TorchFix doesn't understand that `param` is a Torch tensor.
So to prevent false positives (maybe it's not PyTorch code at all and just something has a valid attribute name `require_grad`), it only complains when the value is a boolean literal.

Having said that, it's probably better to change TorchFix to complain in this case.
The probability of false positives seems very low.

**Comment by EgShes** [comment]
I agree with you. Looking forward to adding this functionality.
