### ISSUE TITLE
[HUD] missing information about some jobs

### ISSUE THREAD

**Issue by DanilBaibak** [pytorch/test-infra#5103]
At least two jobs are missing in the list of jobs on HUD:
* `linux-jammy-py3.8-gcc11 / build`
* `linux-focal-cuda12.1-py3.10-gcc9 / build`

The problem is not related to the ARC runners. I tested this on a [separate PR](https://github.com/pytorch/pytorch/pull/124281) where I switched all jobs to dynamic scaling runners.
<img width="1448" alt="Screenshot 2024-04-17 at 16 39 38" src="https://github.com/pytorch/test-infra/assets/3964975/73d8f8e8-b318-4d9c-b23d-2dbbbff93c61">

**Comment by clee2000** [comment]
Did some light digging, this is due to the trie search.  `linux-jammy-py3.8-gcc11 / build` finds and then gets overwritten by `linux-jammy-py3.8-gcc11-no-ops / build` or `linux-jammy-py3.8-gcc11-pch / build`.  `linux-focal-cuda12.1-py3.10-gcc9 / build` finds and then gets overwritten by `linux-focal-cuda12.1-py3.10-gcc9-bazel-test / build-and-test (default, 1, 1, linux.4xlarge.nvidia.gpu)` or `linux-focal-cuda12.1-py3.10-gcc9-sm86 / build`

AI: Make the search stricter
Future AI: stop using names as the identifiers for jobs, just show the entire workflow
