### ISSUE TITLE
Rebase and merge fails cryptically

### ISSUE THREAD

**Issue by huydhn** [pytorch/test-infra#836]
I'm currently seeing a case where rebase and merge fails cryptically, possibly due to the use of ghstack https://github.com/pytorch/pytorch/pull/85920#issuecomment-1264482290

- Rebase failed: https://github.com/pytorch/pytorch/pull/85920#issuecomment-1264484385
- Merge job was also failed: https://github.com/pytorch/pytorch/pull/85920#issuecomment-1264484904

It's weird.

cc @clee2000 @ZainRizvi @pytorch/pytorch-dev-infra

**Comment by ZainRizvi** [comment]
This affects PRs that have been merged and then reverted.

**Comment by clee2000** [comment]
another instance here https://github.com/pytorch/pytorch/pull/87094#issuecomment-1291288835 but pr was not merged and reverted

**Comment by clee2000** [comment]
I'm going to close this since https://github.com/pytorch/pytorch/pull/91337 got merged.  I think it should resolve most of the issues regarding the weird rebase errors we've seen so far.  

If this issue continues or someone finds another bug, please feel free to reopen this issue or create a new one.
